### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by allensuvorov** [allensuvorov/proxy#1]
- [ ] Linter
- [ ] Local end-to-end testing in Docker

**Comment by allensuvorov** [comment]
- [x] caching in the map
- [ ] decouple handler and client, put into separate functions - can test
- [ ] context for flow control, to free-up resources if request is cancelled.
- [x] timeouts (as of now open connections stay open forever)

**Comment by allensuvorov** [comment]
Backlog:
- [ ] can we move reqRes map so it's not a global var? [Article](https://blog.canopas.com/approach-to-avoid-accessing-variables-globally-in-golang-2019b234762)
- [ ] Finetune [mutex RW](https://pkg.go.dev/sync#RWMutex)
